config/routes.rb
Rails.application.routes.draw do

	namespace :casein do
		resources :customers
    resources :contacts
    resources :abouts
    resources :images
	end

 root 'homes#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  
end

app/controllers/casein/abouts_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class AboutsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Abouts'
  		@abouts = About.order(sort_order(:about_us)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View about'
      @about = About.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new about'
    	@about = About.new
    end

    def create
      @about = About.new about_params
    
      if @about.save
        flash[:notice] = 'About created'
        redirect_to casein_abouts_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new about'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update about'
      
      @about = About.find params[:id]
    
      if @about.update_attributes about_params
        flash[:notice] = 'About has been updated'
        redirect_to casein_abouts_path
      else
        flash.now[:warning] = 'There were problems when trying to update this about'
        render :action => :show
      end
    end
 
    def destroy
      @about = About.find params[:id]

      @about.destroy
      flash[:notice] = 'About has been deleted'
      redirect_to casein_abouts_path
    end
  
    private
      
      def about_params
        params.require(:about).permit(:about_us)
      end

  end
end

app/controllers/casein/contacts_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class ContactsController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Contacts'
  		@contacts = Contact.order(sort_order(:address)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View contact'
      @contact = Contact.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new contact'
    	@contact = Contact.new
    end

    def create
      @contact = Contact.new contact_params
    
      if @contact.save
        flash[:notice] = 'Contact created'
        redirect_to casein_contacts_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new contact'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update contact'
      
      @contact = Contact.find params[:id]
    
      if @contact.update_attributes contact_params
        flash[:notice] = 'Contact has been updated'
        redirect_to casein_contacts_path
      else
        flash.now[:warning] = 'There were problems when trying to update this contact'
        render :action => :show
      end
    end
 
    def destroy
      @contact = Contact.find params[:id]

      @contact.destroy
      flash[:notice] = 'Contact has been deleted'
      redirect_to casein_contacts_path
    end
  
    private
      
      def contact_params
        params.require(:contact).permit(:address, :zipcode, :lat, :lng)
      end

  end
end

app/controllers/casein/customers_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class CustomersController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Customers'
  		@customers = Customer.order(sort_order(:name)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View customer'
      @customer = Customer.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new customer'
    	@customer = Customer.new
    end

    def create
      @customer = Customer.new customer_params
    
      if @customer.save
        flash[:notice] = 'Customer created'
        redirect_to casein_customers_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new customer'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update customer'
      
      @customer = Customer.find params[:id]
    
      if @customer.update_attributes customer_params
        flash[:notice] = 'Customer has been updated'
        redirect_to casein_customers_path
      else
        flash.now[:warning] = 'There were problems when trying to update this customer'
        render :action => :show
      end
    end
 
    def destroy
      @customer = Customer.find params[:id]

      @customer.destroy
      flash[:notice] = 'Customer has been deleted'
      redirect_to casein_customers_path
    end
  
    private
      
      def customer_params
        params.require(:customer).permit(:name, :age)
      end

  end
end

app/controllers/casein/images_controller.rb
# Scaffolding generated by Casein v5.0.1.0

module Casein
  class ImagesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Images'
  		@images = Image.order(sort_order(:created_at)).paginate :page => params[:page]
    end
  
    def show
      @casein_page_title = 'View image'
      @image = Image.find params[:id]
    end
  
    def new
      @casein_page_title = 'Add a new image'
    	@image = Image.new
    end

    def create
      @image = Image.new image_params
    
      if @image.save
        flash[:notice] = 'Image created'
        redirect_to casein_images_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new image'
        render :action => :new
      end
    end
  
    def update
      @casein_page_title = 'Update image'
      
      @image = Image.find params[:id]
    
      if @image.update_attributes image_params
        flash[:notice] = 'Image has been updated'
        redirect_to casein_images_path
      else
        flash.now[:warning] = 'There were problems when trying to update this image'
        render :action => :show
      end
    end
 
    def destroy
      @image = Image.find params[:id]

      @image.destroy
      flash[:notice] = 'Image has been deleted'
      redirect_to casein_images_path
    end
  
    private
      
      def image_params
        params.require(:image).permit(:avatar)
      end

  end
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'Casein'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'casein/casein.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'donotreply@caseincms.com'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for :controller => :casein, :action => :blank
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end
    
  end
end

app/views/casein/customers/_form.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->


<div class="row">
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :name %>
	</div>
	<div class="col-lg-6">
		<%= casein_text_field f, f.object, :age %>
	</div>
</div>

app/views/casein/customers/_table.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<table class="table table-striped table-hover table-condensed">
	<thead>
		<tr>
			<th><%= casein_sort_link "Name", :name %></th>
			<th><%= casein_sort_link "Age", :age %></th>
			<th>&nbsp;</th>
		</tr>
	</thead>
	
	<% customers.each do |customer| %>
		<tr>
			<td><%= casein_table_cell_link customer.name, casein_customer_path(customer) %></td>
			<td><%= casein_table_cell_link customer.age, casein_customer_path(customer) %></td>
			<td class="delete">
				<%= link_to(casein_show_row_icon("trash"), casein_customer_path(customer), :method => :delete, :data => { :confirm => "Are you sure you want to delete this customer?" }) %>
			</td>
		</tr>
	<% end %>
</table>

app/views/casein/customers/index.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>Customers<%= casein_pagination_details @customers %></h2>

<%= render :partial => 'casein/customers/table', :locals => { :customers => @customers } %>

<div class="text-center">
	<%= will_paginate @customers %>
</div>

<%= content_for :sidebar do %>

	<li><%= link_to "#{casein_show_icon "plus-sign"}Add a new customer".html_safe, new_casein_customer_path %></li>

<% end %>

app/views/casein/customers/new.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>Add a new customer</h2>

<%= form_for @customer, :url => casein_customers_path do |f| %>
	
	<%= render :partial => 'casein/customers/form', :locals => { :f => f } %>
	
	<p class="submits">
		<%= link_to 'Cancel', casein_customers_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Add new customer", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_customers_path %></li>
<% end %>

app/views/casein/customers/show.html.erb
<!-- Scaffolding generated by Casein v5.0.1.0 -->

<h2>View customer</h2>

<%= form_for @customer, :url => casein_customer_path(@customer) do |f| %>

	<%= render :partial => 'casein/customers/form', :locals => { :f => f } %>
	
	<p class="submits">
	  	<%= link_to 'Cancel', casein_customers_path, :class => 'btn btn-mini btn-danger' %>
		<%= f.submit "Save changes", :class => "btn btn-mini btn-primary" %>
	</p>

<% end %>

<%= content_for :sidebar do %>
	<li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_customers_path %></li>
<% end %>